server:
  port: 6150
  servlet:
    context-path: /

my:
  propereties:
    kakao:
      clientId:
      authBaseUrl:
      apiBaseUrl:
      redirectUrl:
      grantType: "authorization_code"

spring:
  profiles:
    active:
      - dev
    include:
      - credentials
  application:
    name: trip-in-my-room
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    serialization:
      write-null-map-values: false
    deserialization:
      accept-single-value-as-array: true

  jpa:
    hibernate:
      ddl-auto: create

amazon:
  s3:
    directoryPath: storyPictures

cloud:
  aws:
    s3:
      bucket: tripinmyroom
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: false
